### ISSUE TITLE
I don't get it?

### ISSUE THREAD

**Issue by skyisthela** [doniel-t/aniwave-discord-presence#2]
not sure where to ask but, i'm not sure how to install it? i cloned it and added the extension, but i have no idea what it meant by server directory of the repo

**Comment by doniel-t** [comment]
@skyisthela 
The project works kinda like this:
`chrome extension` gets data from aniwave 
`nodejs server` runs in the background and gets the data from the chrome extension and talks to discord to create a rich presence
`client_id` this is the id that authenticates you on discord and where you tell discord that the presence should be shown on your discord account

### In summary:
You need to have the chrome extension installed and the node server running on your machine.
The server is located in the directory `aniwave-discord-presence-server` which is located at the root of the repository
1. Make sure nodeJS is installed
2. Open a terminal in the directory and install the dependencies with `npm install`
3. Now create a file called `.env` and write `CLIENT_ID=replace_this_with_your_discord_application_id`
4. Now (in the same terminal from before) run `npm run dev` to start the server

This is also written down in the readme with more info (such as links) but i can give you a step by step guide if it wont work after trying this

**Comment by skyisthela** [comment]
> @skyisthela The project works kinda like this: `chrome extension` gets data from aniwave `nodejs server` runs in the background and gets the data from the chrome extension and talks to discord to create a rich presence `client_id` this is the id that authenticates you on discord and where you tell discord that the presence should be shown on your discord account
> 
> ### In summary:
> You need to have the chrome extension installed and the node server running on your machine. The server is located in the directory `aniwave-discord-presence-server` which is located at the root of the repository
> 
> 1. Make sure nodeJS is installed
> 2. Open a terminal in the directory and install the dependencies with `npm install`
> 3. Now create a file called `.env` and write `CLIENT_ID=replace_this_with_your_discord_application_id`
> 4. Now (in the same terminal from before) run `npm run dev` to start the server
> 
> This is also written down in the readme with more info (such as links) but i can give you a step by step guide if it wont work after trying this

thanks for replying. I do have nodejs installed. In terminal, I cded into the aniwave discord presence folder and this showed up 
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/1eac685c-5f13-4183-b007-ea68868589af)

**Comment by skyisthela** [comment]
Thanks for replying. So I did what you said but when you say a file do you mean a folder specifically or a text file? I created a text file, inside it was the client ID, however the terminal was running and showing what anime i was watching but not discord

**Comment by doniel-t** [comment]
It has to be a .env file not a text file - i assume yours looks probably similiar to this .env.txt (with .txt hidden by windows)

i did some research and apparently its fine to expose the application id so i just added my id (which removes the step of creating a discord application)

So you should just be able to re-clone the repo, `npm install` the dependencies and run it

**Comment by skyisthela** [comment]
ok, to make things safe, i deleted node js and the git clone. when i reinstalled them however there seems to already have an .env file created? with a random(?) client ID as well. but now there's an entirely different issue. 
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/695492f4-ea48-469c-966d-45da8cba4275)
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/4b56d9cb-7d91-4894-8fda-c9b32c361fe4)
EVERYTHING is undead unluck apparently XD

sorry im bothering u with this tho 💀

**Comment by skyisthela** [comment]
i read the other issue here and you mentioned that it might be because there are multiple tabs open (which thankfully i did not) the other dude also mentioned that they logged out which fixed the isssue. to make things _even_ safer, i restarted my pc, and did everything from scratch and logged out, the only difference is 
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/b3df61c3-4fba-461b-af2b-b46f05488d82)
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/0fd085e9-16b7-4778-9e77-44d3b717adc4)

it only shows the actual anime briefly then goes back to undead unluck, are you actually just a huge chance of undead unluck XD

**Comment by doniel-t** [comment]
i tried to reproduce the bug but wasnt able to.

For some anime it has to refetch the episode number which is intended behaviour, because aniwave re-hydrates the website after a certain time.
This is why (in the case of owarimonogatari) it shows:
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/56281274/3f631d70-fe58-48ac-ab72-d7b236be1872)

this gets refetched after a couple of seconds though (because the url changes) and shows the right episode number like in the image below

![image](https://github.com/doniel-t/aniwave-discord-presence/assets/56281274/f08a2b57-1b28-4385-856b-985966005654)

![image](https://github.com/doniel-t/aniwave-discord-presence/assets/56281274/2a8fae2e-6be1-46c4-b9c4-5b5d829bc090)

i tried watching undead unlucky before switching to owarimonogatari like you did but it still worked regardless.

If you want to im down to add you on discord and try to debug it there with you

**Comment by skyisthela** [comment]
yeah i think it's better if you add me, my discord is skyisthela.
also i did not watch undead unluck prio to owarimonogatari, it just randomly showed up. this time i'm watching dungeon meshi but it shows classroom of the elite instead
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/ed256480-e682-4e58-ad3a-a7afa46ccd60)
![image](https://github.com/doniel-t/aniwave-discord-presence/assets/150245867/3d6a3ea4-dae5-4aa2-a2c7-d24fde7dcfb1)
